---
scs_cluster_stack_cmd: "{{ scs_cluster_stack_bin }} --conf={{ scs_cluster_stack_conf }}"
scs_cluster_stack_conf: "{{ scs_cluster_stack_conf_dir }}/scs_cluster_stack.yaml"
scs_cluster_stack_conf_dir: "/etc/scs_cluster_stack"
scs_cluster_stack_group: "{{ scs_cluster_stack_user }}"
scs_cluster_stack_home: "/var/lib/scs_cluster_stack"
scs_cluster_stack_logfile: "/var/log/scs_cluster_stack.log"
scs_cluster_stack_logrotat_dir: "/etc/logrotate.d"
scs_cluster_stack_logrotate: "{{ scs_cluster_stack_logrotat_dir }}/scs_cluster_stack"
scs_cluster_stack_repo: "https://github.com/egypcio/scs-kaas-scripts"
scs_cluster_stack_repo_branch: "main-debian-fixes"
scs_cluster_stack_repo_commit: "ce630c0bdaee026307c10e8d4d52168318cc433c"
scs_cluster_stack_service: "scs_cluster_stack"
scs_cluster_stack_service_unit: "/etc/systemd/system/{{ scs_cluster_stack_service }}.service"
scs_cluster_stack_src_dir: "{{ scs_cluster_stack_home }}/src"
scs_cluster_stack_user: "scs_cluster_stack"
