---
scripts_only: false

#
# scs
#

scs_cs_group: "{{ scs_cs_user }}"
scs_cs_repo_cso: "oci://registry.scs.community/cluster-stacks/cso"
scs_cs_user: "scs2"
scs_cs_user_home: "/var/lib/{{ scs_cs_user }}"

#
# docker
#

docker_apt_repo: "https://download.docker.com/linux/{{ansible_distribution|lower}}"
docker_apt_repo_filename: "docker"
docker_apt_repo_key: "https://download.docker.com/linux/{{ansible_distribution|lower}}/gpg"
docker_apt_sign_key: "/etc/apt/trusted.gpg.d/{{docker_apt_repo_filename}}.asc"
docker_gpg_key: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
docker_gpg_keyserver: "https://keys.openpgp.org"

#
# openstack
#

openstack_application_credential_id: "{{ lookup('env', 'OS_APPLICATION_CREDENTIAL_ID') }}"
openstack_application_credential_secret: "{{ lookup('env', 'OS_APPLICATION_CREDENTIAL_SECRET') }}"
openstack_auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
openstack_bastion_flavor: "SCS-2V-4-20s"
openstack_cloud: "{{ lookup('env', 'OS_CLOUD') }}"
openstack_cloud_cacert_b64: "b3BlbnN0YWNr"
openstack_cloud_name: "{{ openstack_cloud }}"
openstack_clouds_yaml: "{{scs_cs_user_home}}/.config/openstack/clouds.yaml"
openstack_clouds_yaml_b64: "b3BlbnN0YWNr"
openstack_controlplane_flavor: "{{ openstack_bastion_flavor }}"
openstack_dns_servers: "9.9.9.9, 8.8.8.8, 1.1.1.1"
openstack_external_network_id: "{{ lookup('env', 'OS_EXTERNAL_NETWORK_ID') }}"
openstack_failure_domain: "myfailuredomain.local"
openstack_image_name: "Ubuntu 24.04"
openstack_interface: "{{ lookup('env', 'OS_INTERFACE') }}"
openstack_node_flavor: "{{ openstack_bastion_flavor }}"
openstack_orc_release: "2.4.0"
openstack_orc_repo: "https://github.com/k-orc/openstack-resource-controller"
openstack_orc_yaml: "{{openstack_orc_repo}}/releases/download/v{{openstack_orc_release}}/install.yaml"
openstack_password: "{{ lookup('env', 'OS_AUTH_PASSWORD') }}"
openstack_provider_release: "0.12.6"
openstack_region_name: "{{ lookup('env', 'OS_REGION_NAME') }}"
openstack_secret_name: "{{ lookup('env', 'OS_SECRET') }}"
openstack_ssh_key_name: "mysshkey"
openstack_tenant_id: "{{ lookup('env', 'OS_TENANT_ID') }}"
openstack_username: "{{ lookup('env', 'OS_AUTH_USERNAME') }}"
openstack_worker_flavor: "{{ openstack_bastion_flavor }}"
openstack_worker_rootdisk_size: 32

#
# kubernetes components
#

k3s_apply_role: true
k3s_bin: "/usr/local/bin/k3s"
k3s_capi_release: "0.3.0"
k3s_cloud_conf_b64: ""

kind_release: "0.31.0"

kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"

oras_release: "1.3.0"

kubernetes_release: "{{kubernetes_release_version}}.{{kubernetes_release_version_patch}}"
kubernetes_release_version: "1.33"
kubernetes_release_version_patch: "7"
kubernetes_service_host: "127.0.0.1"
kubernetes_service_port: 6443

csctl_bin: "/usr/local/bin/csctl"
csctl_bin_sha256: "3f8344093e93c5c30a622bb81cb92bd31371882e91010d7b303914cceddbca51"
csctl_bin_url: "https://github.com/SovereignCloudStack/csctl/releases/download/v{{csctl_release}}/csctl_{{csctl_release}}_linux_amd64.tar.gz"
csctl_release: "0.0.5"

clusterctl_bin: "/usr/local/bin/clusterctl"
clusterctl_bin_sha256: "c80f6e7451355b34cca9f0ddf087bb4fa14a3fcef7833614b3d59e9b4b345036"
clusterctl_bin_url: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v{{clusterctl_release}}/clusterctl-linux-amd64"
clusterctl_release: "1.10.10"

helm_bin: "/usr/local/bin/helm"
helm_bin_sha256: "c77e9e7c1cc96e066bd240d190d1beed9a6b08060b2043ef0862c4f865eca08f"
helm_bin_url: "https://get.helm.sh/helm-v{{helm_release}}-linux-amd64.tar.gz"
helm_release: "4.0.0"

kubectl_bin: "/usr/local/bin/kubectl"
kubectl_bin_sha256: "9591f3d75e1581f3f7392e6ad119aab2f28ae7d6c6e083dc5d22469667f27253"
kubectl_bin_url: "https://dl.k8s.io/release/v{{kubernetes_release}}/bin/linux/amd64/kubectl"
kubectl_release: "{{kubernetes_release}}"

#
# cluster stack settings
#

cluster_api_contract: "v1beta1"
cluster_api_contract_addons: "{{ cluster_api_contract }}"
cluster_api_contract_clusterstack: "v1alpha1"
cluster_api_contract_clusterstack_addons: "{{ cluster_api_contract_clusterstack }}"
cluster_api_contract_clusterstack_csctl: "{{ cluster_api_contract_clusterstack }}"
cluster_api_contract_clusterstack_infrastructure: "{{ cluster_api_contract_clusterstack }}"
cluster_cidr_pods: "172.16.0.0/16"
cluster_cidr_services: "10.96.0.0/12"
cluster_cidr_managed_subnet: "10.96.0.0/24"
cluster_class: "openstack-{{cluster_series}}-{{kubernetes_release_version}}-{{cluster_series_version}}"
cluster_controlplane_replicas: 1
cluster_ctrlnodes: 1
cluster_external_network_id: "{{ openstack_external_network_id }}"
cluster_name: "mycluster"
cluster_namespace: "mynamespace"
cluster_secret: "{{ openstack_secret_name }}"
cluster_series: "scs2"
cluster_series_channel: "stable"
cluster_series_version: "v4"
cluster_services_domain: "mydomain.local"
cluster_workers_replicas: 1
cluster_wrkrnodes: 1
