---
scs_cluster_stack_cmd: "{{ scs_cluster_stack_bin }} --conf: {{ scs_cluster_stack_conf }}"
scs_cluster_stack_conf: "{{ scs_cluster_stack_conf_dir }}/scs_cluster_stack.yaml"
scs_cluster_stack_conf_dir: "/etc/scs_cluster_stack"
scs_cluster_stack_group: "{{ scs_cluster_stack_user }}"
scs_cluster_stack_home: "/var/lib/scs_cluster_stack"
scs_cluster_stack_logfile: "/var/log/scs_cluster_stack.log"
scs_cluster_stack_logrotat_dir: "/etc/logrotate.d"
scs_cluster_stack_logrotate: "{{ scs_cluster_stack_logrotat_dir }}/scs_cluster_stack"
scs_cluster_stack_repo: "https://github.com/egypcio/scs-kaas-scripts"
scs_cluster_stack_repo_branch: "main-debian-fixes"
scs_cluster_stack_repo_commit: "ce630c0bdaee026307c10e8d4d52168318cc433c"
scs_cluster_stack_service: "scs_cluster_stack"
scs_cluster_stack_service_unit: "/etc/systemd/system/{{ scs_cluster_stack_service }}.service"
scs_cluster_stack_src_dir: "{{ scs_cluster_stack_home }}/src"
scs_cluster_stack_user: "scs_cluster_stack"

#
# docker
#

docker_apt_repo: "https://download.docker.com/linux/{{ansible_distribution|lower}}"
docker_apt_repo_filename: "docker"
docker_apt_repo_key: "https://download.docker.com/linux/{{ansible_distribution|lower}}/gpg"
docker_apt_sign_key: "/etc/apt/trusted.gpg.d/{{docker_apt_repo_filename}}.asc"
docker_gpg_key: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
docker_gpg_keyserver: "https://keys.openpgp.org"

#
# cluster stack components
#

capi_release: "1.11.3"         # clusterctl
helm_release: "4.0.0"          # helm
kind_release: "0.30.0"         # kind
kubernetes_release: "1.33.4"   # kubectl

clusterctl_bin_url: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v${capi_release}/clusterctl-linux-amd64"
kind_bin_url: "https://github.com/kubernetes-sigs/kind/releases/download/v${kind_release}/kind-linux-amd64"
kubectl_bin_url_: "https://dl.k8s.io/release/v${kubernetes_release}/bin/linux/amd64/kubectl"
