---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install dependencies
  apt:
    name: "{{ d }}"
    state: present
  loop: "{{ scs_cluster_stack_dependencies }}"
  loop_control:
    loop_var: d

# https://docs.ansible.com/ansible/latest/collections/community/general/snap_module.html
- name: Install snap core
  snap:
    name: core
    state: present
  when: ansible_facts.distribution == 'Ubuntu'
