---
- name: Update apt Cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install dependencies
  apt:
    name: "{{ d }}"
    state: present
  loop: "{{ scs_cluster_stack_dependencies }}"
  loop_control:
    loop_var: d

# https://docs.ansible.com/ansible/latest/collections/community/general/snap_module.html
- name: Install snap core
  snap:
    name: core
    state: present
  when: ansible_facts.distribution == 'Ubuntu'

# https://github.com/geerlingguy/ansible-role-kubernetes/blob/master/tasks/sysctl-setup.yml
- name: Ensure module "br_netfilter" is loaded
  modprobe:
    name: br_netfilter
    state: present
    persistent: present
  when: not ansible_virtualization_type == "docker"

# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic
- name: Let iptables see bridged traffic
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
  when: >
    ( ansible_facts.distribution != 'Debian'
      or ansible_facts.distribution_major_version | int < 10
    ) and not ansible_virtualization_type == "docker"
