---
- name: Ensure "{{ scs_cluster_stack_user }}" group is present
  become: true
  group:
    name: "{{ scs_cluster_stack_group }}"
    state: present

- name: Ensure "{{ scs_cluster_stack_user }}" user is present
  become: true
  user:
    home: "{{ scs_cluster_stack_home }}"
    create_home: true
    comment: "{{ scs_cluster_stack_user }}"
    name: "{{ scs_cluster_stack_user }}"
    shell: "/bin/false"
    groups: "{{ scs_cluster_stack_user }}"
    password: "{{ lookup('community.general.random_string', base64=true) | password_hash }}"
    password_lock: true
    update_password: on_create
    system: true
    state: present
  register: scs_cluster_stack_user_created

- name: Enforce permissions on "{{ scs_cluster_stack_home }}"
  become: true
  file:
    dest: "{{ scs_cluster_stack_home }}"
    owner: "{{ scs_cluster_stack_user }}"
    group: "{{ scs_cluster_stack_group }}"
    mode: 0750
  when: scs_cluster_stack_user_created.changed

- name: Generate random token key
  command:
    cmd: openssl rand -base64 32
  register: random_token_key
  args:
    creates: "{{ scs_cluster_stack_home }}/token"

- name: Copy token to a file
  become: true
  copy:
    content: "{{ random_token_key.stdout }}"
    dest:  "{{ scs_cluster_stack_home }}/token"
    mode: 0440
    owner: "{{ scs_cluster_stack_user }}"
    group: "{{ scs_cluster_stack_group }}"
  when: random_token_key.changed

- name: Ensure "{{scs_cluster_stack_user}}" is a member of "ssl-cert"
  become: true
  user:
    name: "{{ scs_cluster_stack_user }}"
    groups: "ssl-cert"
    append: true
