---
- name: Setup apt-key, when older than Debian bullseye
  get_url:
    keyserver: "{{ docker_gpg_keyserver }}"
    id: "{{ docker_gpg_key }}"
    state: present
  when: "ansible_distribution_major_version|int < 11"

- name: Setup apt-key, when Debian bullseye or above
  get_url:
    url: "{{ docker_apt_repo_key }}"
    dest: "{{ docker_apt_sign_key }}"
    mode: '0444'
  when: "ansible_distribution_major_version|int >= 11"

- name: Configure the apt repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by={{docker_apt_sign_key}}] {{docker_apt_repo}} {{ansible_lsb.codename}} stable"
    filename: "{{ docker_apt_repo_filename }}"

- name: Install Docker packages
  apt:
    name:
      - containerd.io
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
    state: present

- name: Ensure we set "net.ipv4.tcp_mtu_probing=1" as sysctl
  sysctl:
    name: "net.ipv4.tcp_mtu_probing"
    value: "1"
    sysctl_set: true
    state: present
    reload: true
