---
- name: Apply 'k3s' role
  include_role:
    name: k3s
  vars:
    k3s_agent:
      node-label:
        - "cluster-api=true"
        - "cluster-stack=true"
        - "control-plane=true"
        - "worker=true"
        - "workload=true"
  when: k3s_apply_role
