---
- name: Apply 'k3s' role
  block:

    - name: Include tasks and define vars
      include_role:
        name: k3s
      vars:
        k3s_agent:
          node-label:
            - "cluster-api=true"
            - "cluster-stack=true"
            - "control-plane=true"
            - "worker=true"
            - "workload=true"

    - name: Generate bash completions for "k3s"
      become: true
      command: "{{ k3s_bin }} completion bash"
      register: completions_k3s
      args:
        creates: "/etc/bash_completion.d/k3s"

    - name: Copy completions for "k3s" to a file
      become: true
      copy:
        content: "{{ completions_k3s.stdout }}"
        dest:  "/etc/bash_completion.d/k3s"
        mode: 0444
      when: completions_k3s.changed

  when: k3s_apply_role | bool



- name: Install 'kind' instead of 'k3s' as the management cluster
  block:

    - name: Check if "kind" exists
      stat:
        path: "{{ kind_bin }}"
      register: check_kind
    
    - name: Get "kind"
      become: true
      become_user: "{{ scs_cs_user }}"
      command: "go install sigs.k8s.io/kind@v{{kind_release}}"
      when: not check_kind.stat.exists
      register: get_kind

    - name: Move "kind" binary
      become: true
      copy:
        remote_src: true
        src: "{{scs_cs_user_home}}/go/bin/kind"
        dest: "{{ kind_bin }}"
        mode: 0555
      when: get_kind.changed
    
    - name: Strip "kind"
      become: true
      command: "strip {{ kind_bin }}"
      when: get_kind.changed
    
    - name: Generate bash completions for "kind"
      become: true
      command: "{{ kind_bin }} completion bash"
      register: completions_kind
      args:
        creates: "/etc/bash_completion.d/kind"
    
    - name: Copy completions for "kind" to a file
      become: true
      copy:
        content: "{{ completions_kind.stdout }}"
        dest:  "/etc/bash_completion.d/kind"
        mode: 0444
      when: completions_kind.changed

    - name: Create management cluster with 'kind'
      command: "{{kind_bin}} create cluster --image kindest/node:v{{kubernetes_release}}"

  when: not k3s_apply_role | bool
