---
- name: Check if "clusterctl" exists
  stat:
    path: "{{ clusterctl_bin }}"
  register: check_clusterctl

- name: Get "clusterctl"
  become: true
  get_url:
    url: "{{ clusterctl_bin_url }}"
    dest: "{{ clusterctl_bin }}"
    checksum: "sha256:{{clusterctl_bin_sha256}}"
    mode: 0755
  when: not check_clusterctl.stat.exists
  register: get_clusterctl

- name: Strip "clusterctl"
  become: true
  command:
    cmd: "strip {{ clusterctl_bin }}"
  when: get_clusterctl.changed

- name: Get "helm" if it does not exist
  become: true
  unarchive:
    dest: "/usr/local/bin/"
    include:
      - linux-amd64/helm
    extra_opts: "--strip-components=1"
    mode: 0755
    remote_src: true
    src: "{{ helm_bin_url }}"
  args:
    creates: "{{ helm_bin }}"
  register: get_helm

- name: Check if "kubectl" exists
  stat:
    path: "{{ kubectl_bin }}"
  register: check_kubectl

- name: Get "kubectl"
  become: true
  get_url:
    url: "{{ kubectl_bin_url }}"
    dest: "{{ kubectl_bin }}"
    checksum: "sha256:{{kubectl_bin_sha256}}"
    mode: 0755
  when: not check_kubectl.stat.exists
  register: get_kubectl

- name: Strip "kubectl"
  become: true
  command:
    cmd: "strip {{ kubectl_bin }}"
  when: get_kubectl.changed
