---
- name: Template "tool-install-oras.sh"
  become: true
  template:
    src: tool-install-oras.sh.j2
    dest: "{{scs_cluster_stack_home}}/tool-install-oras.sh"
    mode: 0555

- name: Check if "clusterctl" exists
  stat:
    path: "{{ clusterctl_bin }}"
  register: check_clusterctl

- name: Get "clusterctl"
  become: true
  get_url:
    url: "{{ clusterctl_bin_url }}"
    dest: "{{ clusterctl_bin }}"
    checksum: "sha256:{{clusterctl_bin_sha256}}"
    mode: 0755
  when: not check_clusterctl.stat.exists
  register: get_clusterctl

- name: Strip "clusterctl"
  become: true
  command:
    cmd: "strip {{ clusterctl_bin }}"
  when: get_clusterctl.changed

- name: Generate bash completions for "clusterctl"
  become: true
  command:
    cmd: "{{ clusterctl_bin }} completion bash"
  register: completions_clusterctl
  args:
    creates: "/etc/bash_completion.d/clusterctl"

- name: Copy completions for "clusterctl" to a file
  become: true
  copy:
    content: "{{ completions_clusterctl.stdout }}"
    dest:  "/etc/bash_completion.d/clusterctl"
    mode: 0444
  when: completions_clusterctl.changed

- name: Get "helm"
  become: true
  unarchive:
    dest: "/usr/local/bin/"
    include:
      - linux-amd64/helm
    extra_opts: "--strip-components=1"
    mode: 0755
    remote_src: true
    src: "{{ helm_bin_url }}"
  args:
    creates: "{{ helm_bin }}"
  register: get_helm

- name: Get "envsubst"
  become: true
  command:
    cmd: "go install github.com/drone/envsubst/v2/cmd/envsubst@{{envsubst_release}}"
  register: get_envsubst
  args:
    creates: "{{ envsubst_bin }}"
  environment:
    GOBIN: "/usr/local/bin"

- name: Strip "envsubst"
  become: true
  command:
    cmd: "strip {{ envsubst_bin }}"
  when: get_envsubst.changed
