---
- name: Check if we have any 'kind' clusters already
  command:
    cmd: "kind get clusters"
  register: kind_get_clusters

- name: Create 'kind' cluster
  command:
    cmd: "kind create cluster"
  when: kind_get_clusters.stdout == ""
