---
- name: Template "{{scs_cluster_stack_home}}/capi-k8s-specs.yaml"
  become: true
  template:
    src: capi-k8s-specs.yaml.j2
    dest: "{{scs_cluster_stack_home}}/capi-k8s-specs.yaml"
    mode: 0440

- name: Template "{{scs_cluster_stack_home}}/capi-k8s-vars.rc"
  become: true
  template:
    src: capi-k8s-vars.rc.j2
    dest: "{{scs_cluster_stack_home}}/capi-k8s-vars.rc"
    mode: 0440

- name: Initialize cluster
  become: true
  shell:
    cmd: |
      source {{scs_cluster_stack_home}}/capi-k8s-vars.rc \
      && clusterctl init -b canonical-kubernetes -c canonical-kubernetes -i openstack --kubeconfig {{ kubeconfig_path }}
  args:
    executable: /bin/bash

- name: Install OpenStack Resource Controller (ORC) via "k3s"
  become: true
  shell:
    cmd: |
      source {{scs_cluster_stack_home}}/capi-k8s-vars.rc \
      {{ k3s_bin }} kubectl apply -f {{ openstack_orc_yaml }}
  args:
    executable: /bin/bash

- name: Checkout "{{ canonical_capi_repo }}"
  become: true
  git:
    depth: 1
    dest: "{{scs_cluster_stack_home}}/cluster-api-k8s"
    repo: "{{ canonical_capi_repo }}"
    single_branch: true
    update: false
    version: "{{ canonical_capi_version }}"
  environment:
    GIT_TERMINAL_PROMPT: 0

- name: Generate cluster specs from template
  become: true
  shell:
    chdir: "{{scs_cluster_stack_home}}/cluster-api-k8s"
    cmd: |
      source {{scs_cluster_stack_home}}/capi-k8s-vars.rc \
      && clusterctl generate cluster {{ cluster_name }} --kubernetes-version v{{kubernetes_release}} --from {{scs_cluster_stack_home}}/capi-k8s-specs.yaml \
         > {{scs_cluster_stack_home}}/cluster_{{cluster_name}}.yaml
  args:
    executable: /bin/bash

- name: Apply cluster specs
  become: true
  shell:
    chdir: "{{scs_cluster_stack_home}}/cluster-api-k8s"
    cmd: |
      source {{scs_cluster_stack_home}}/capi-k8s-vars.rc \
      && {{ k3s_bin }} kubectl apply -f {{scs_cluster_stack_home}}/cluster_{{cluster_name}}.yaml
  args:
    executable: /bin/bash
  ignore_errors: true
  no_log: true

- name: Generate generic secret via "k3s"
  become: true
  shell:
    cmd: |
      source {{scs_cluster_stack_home}}/capi-k8s-vars.rc \
      {{ k3s_bin }} kubectl create secret generic {{cluster_name}} --dry-run=client -o yaml \
      | {{ k3s_bin }} kubectl apply -f - --validate=false
  args:
    executable: /bin/bash

- name: Generate TLS secret via "k3s"
  become: true
  shell:
    cmd: |
      source {{scs_cluster_stack_home}}/capi-k8s-vars.rc \
      {{ k3s_bin }} kubectl create secret tls {{cluster_name}} --dry-run=client -o yaml --cert={{snakeoil_cert}} --key={{snakeoil_key}} \
      | {{ k3s_bin }} kubectl apply -f - --validate=false --insecure-skip-tls-verify
  args:
    executable: /bin/bash
