---
# # https://documentation.ubuntu.com/canonical-kubernetes/latest/capi/howto/provision/
# - name: Clone "{{ scs_cluster_stack_capi_k8s_repo }}" git repository
#   git:
#     repo: "{{ scs_cluster_stack_capi_k8s_repo }}"
#     dest: "{{ scs_cluster_stack_home }}/capi-k8s"
#     single_branch: true
#     version: "{{ scs_cluster_stack_capi_k8s_tag }}"
#     clone: true
#     update: false
#   environment:
#     GIT_TERMINAL_PROMPT: 0
#   when: ansible_facts.distribution == 'Ubuntu'

- name: Template "{{scs_cluster_stack_home}}/capi-k8s-cluster-template.yaml"
  become: true
  template:
    src: capi-k8s-cluster-template.yaml.j2
    dest: "{{scs_cluster_stack_home}}/capi-k8s-cluster-template.yaml"
    mode: 0444

- name: Template "{{scs_cluster_stack_home}}/capi-k8s-vars.rc"
  become: true
  template:
    src: capi-k8s-vars.rc.j2
    dest: "{{scs_cluster_stack_home}}/capi-k8s-vars.rc"
    mode: 0444

# - name: Apply k-ORC as dependency used by "clusterctl"
#   command:
#     cmd: "kubectl apply -f {{ korc_yaml_url }}"

- name: Generate cluster configuration from template
  become: true
  command:
    cmd: "clusterctl generate cluster {{ cluster_name }} -f {{scs_cluster_stack_home}}/capi-k8s-cluster-template.yaml >{{scs_cluster_stack_home}}/cluster_{{cluster_name}}.yaml"
  environment:
    CLUSTER_NAME="{{cluster_name}}"
    CLUSTER_TOPOLOGY=true
    EXP_CLUSTER_RESOURCE_SET=true
    EXP_RUNTIME_SDK=true

- name: Initialize cluster
  become: true
  command:
    cmd: "clusterctl init -b canonical-kubernetes -c canonical-kubernetes -i openstack"
  environment:
    CLUSTER_TOPOLOGY=true
    EXP_CLUSTER_RESOURCE_SET=true
    EXP_RUNTIME_SDK=true
