---
- name: Template "clusterctl.yaml"
  become: true
  template:
    src: clusterctl.yaml.j2
    dest: "{{scs_cs_user_home}}/.config/cluster-api/clusterctl.yaml"
    mode: 0440

- name: Install openstack resources controller (ORC)
  become: true
  command: "kubectl apply -f {{ openstack_orc_yaml }}"

- name: Define labels to the ORC CRD in order to successfully move objects
  become: true
  command: "kubectl label crd {{type}}.openstack.k-orc.cloud clusterctl.cluster.x-k8s.io/move=''"
  loop:
    - servers
    - images
  loop_control:
    loop_var: type

- name: Initialize management cluster using 'k3s'
  become: true
  command: "clusterctl init --kubeconfig {{ kubeconfig_path }} -n {{cluster_namespace}} -i openstack:v{{openstack_provider_release}} --core cluster-api:v{{clusterctl_release}} --bootstrap k3s:v{{k3s_capi_release}} --control-plane k3s:v{{k3s_capi_release}}"
  environment:
    - CLUSTER_TOPOLOGY: true
    - EXP_CLUSTER_RESOURCE_SET: true
    - EXP_RUNTIME_SDK: true
    - KUBECONFIG: "{{ kubeconfig_path }}"
  when: k3s_apply_role | bool

- name: Initialize management cluster using 'kind'
  become: true
  command: "clusterctl init -n {{cluster_namespace}} -i openstack:v{{openstack_provider_release}} --core cluster-api:v{{clusterctl_release}}"
  environment:
    - CLUSTER_TOPOLOGY: true
    - EXP_CLUSTER_RESOURCE_SET: true
    - EXP_RUNTIME_SDK: true
  when: not k3s_apply_role | bool

- name: Request rollout status for CAPI
  become: true
  command: "kubectl -n capi-system rollout status deployment"

- name: Request rollout status for CAPO
  become: true
  command: "kubectl -n capo-system rollout status deployment"

#
# kubectl --kubeconfig=./capi-quickstart.kubeconfig -n kube-system create secret generic cloud-config --from-file=cloud.conf
# kubectl apply --kubeconfig=./capi-quickstart.kubeconfig -f https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/master/manifests/controller-manager/cloud-controller-manager-roles.yaml
# kubectl apply --kubeconfig=./capi-quickstart.kubeconfig -f https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/master/manifests/controller-manager/cloud-controller-manager-role-bindings.yaml
# kubectl apply --kubeconfig=./capi-quickstart.kubeconfig -f https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/master/manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
#
