---
- name: Apply k-ORC as dependency
  command:
    cmd: >
      kubectl apply -f "{{korc_yaml_url}}"
  environment:
    CLUSTER_TOPOLOGY=true
    EXP_CLUSTER_RESOURCE_SET=true
    EXP_RUNTIME_SDK=true

- name: Rollout CAPI
  command:
    cmd: >
     clusterctl init --infrastructure openstack
  environment:
    CLUSTER_TOPOLOGY=true
    EXP_CLUSTER_RESOURCE_SET=true
    EXP_RUNTIME_SDK=true
