---
- name: Template the Cluster Stack Operator manifest
  become: true
  template:
    src: scs-cso.yaml.j2
    dest: "{{scs_cluster_stack_home}}/scs-cso.yaml"
    mode: 0444

- name: Install the Cluster Stack Operator via Helm
  become: true
  shell:
    cmd: |
      source {{scs_cluster_stack_home}}/capi-k8s-vars.rc \
      && helm upgrade --create-namespace \
         --set "octavia_ovn=true" \
         --values "{{scs_cluster_stack_home}}/scs-cso.yaml" \
         -i cso -n cso-system \
         oci://{{ cluster_oci_repo_cso }}
  args:
    executable:  /bin/bash
  environment:
    - CLUSTER_TOPOLOGY: true
    - EXP_CLUSTER_RESOURCE_SET: true
    - EXP_RUNTIME_SDK: true
