---
- name: Template "clouds.yaml"
  become: true
  template:
    src: clouds.yaml.j2
    dest: "{{openstack_clouds_yaml}}"
    mode: 0440

- name: Template "specs-namespace.yaml"
  become: true
  template:
    src: specs-namespace.yaml.j2
    dest: "{{scs_cs_user_home}}/specs-namespace.yaml"
    mode: 0440

- name: Encode "clouds.yaml" into base64
  become: true
  command: "base64 -w 0 {{openstack_clouds_yaml}}"
  register: stdout_base64_openstack_clouds_yaml

- name: Encode "{{kubeconfig_path}}" into base64
  become: true
  command: "base64 -w 0 {{kubeconfig_path}}"
  register: stdout_base64_kubeconfig

- name: Set fact from encoded "clouds.yaml"
  set_fact:
    openstack_clouds_yaml_b64: "{{ stdout_base64_openstack_clouds_yaml.stdout }}"

- name: Set fact from encoded "{{kubeconfig_path}}"
  set_fact:
    kubeconfig_b64: "{{ stdout_base64_kubeconfig.stdout }}"

- name: Ensure we have the namespace available before generating secrets
  become: true
  command: "{{k3s_bin}} kubectl apply -f {{scs_cs_user_home}}/specs-namespace.yaml"

- name: Template "specs-secret-kubeconfig.yaml"
  become: true
  template:
    src: specs-secret-kubeconfig.yaml.j2
    dest: "{{scs_cs_user_home}}/specs-secret-kubeconfig.yaml"
    mode: 0440

- name: Apply "specs-secret-kubeconfig.yaml"
  become: true
  command: "{{k3s_bin}} kubectl apply -f {{scs_cs_user_home}}/specs-secret-kubeconfig.yaml"

- name: Generate generic secret for the cluster
  become: true
  command: "{{k3s_bin}} kubectl create secret generic {{cluster_name}} -n {{cluster_namespace}} --from-file=clouds.yaml={{openstack_clouds_yaml}} --dry-run=client -o yaml"
  register: secrets_cluster

- name: Copy generated secret for the cluster
  become: true
  copy:
    content: "{{ secrets_cluster.stdout }}"
    dest:  "{{scs_cs_user_home}}/.secret-cluster"
    mode: 0440
  when: secrets_cluster.changed

- name: Apply generated secret for the openstack cloud provider
  become: true
  command: "{{k3s_bin}} kubectl apply -f {{scs_cs_user_home}}/.secret-cluster"

- name: Generate generic secret for the openstack cloud provider
  become: true
  command: "{{k3s_bin}} kubectl create secret generic {{openstack_cloud}} -n {{cluster_namespace}} --from-file=clouds.yaml={{openstack_clouds_yaml}} --dry-run=client -o yaml"
  register: secrets_openstack_cloud_provider

- name: Copy generated secret for the openstack cloud provider to a file
  become: true
  copy:
    content: "{{ secrets_openstack_cloud_provider.stdout }}"
    dest:  "{{scs_cs_user_home}}/.secret-os-cloud-provider"
    mode: 0440
  when: secrets_openstack_cloud_provider.changed

- name: Apply generated secret for the openstack cloud provider
  become: true
  command: "{{k3s_bin}} kubectl apply -f {{scs_cs_user_home}}/.secret-os-cloud-provider"

- name: Generate generic secret for CAPO
  become: true
  command: "{{k3s_bin}} kubectl create secret generic openstack -n {{cluster_namespace}} --from-file=clouds.yaml={{openstack_clouds_yaml}} --dry-run=client -o yaml"
  register: secrets_openstack

- name: Copy generated secret for CAPO to a file
  become: true
  copy:
    content: "{{ secrets_openstack.stdout }}"
    dest:  "{{scs_cs_user_home}}/.secret-capo"
    mode: 0440
  when: secrets_openstack.changed

- name: Apply generated secret for CAPO
  become: true
  command: "{{k3s_bin}} kubectl apply -f {{scs_cs_user_home}}/.secret-capo"

- name: Generate generic secret for "clouds-yaml" kube-system
  become: true
  command: "{{k3s_bin}} kubectl create secret generic clouds-yaml -n kube-system --from-file=clouds.yaml={{openstack_clouds_yaml}} --dry-run=client -o yaml"
  register: secrets_kubesys

- name: Copy generated secret for "clouds-yaml" kube-system to a file
  become: true
  copy:
    content: "{{ secrets_kubesys.stdout }}"
    dest:  "{{scs_cs_user_home}}/.secret-kubesys"
    mode: 0440
  when: secrets_kubesys.changed

- name: Generate secret based on "clouds-yaml" kube-system output file for the ClusterResourceSet (CRS)
  become: true
  command: "{{k3s_bin}} kubectl create secret generic clouds-yaml -n {{cluster_namespace}} --from-file={{scs_cs_user_home}}/.secret-kubesys --dry-run=client -o yaml"
  register: secrets_crs

- name: Copy generated secret for "CRS" to a file
  become: true
  copy:
    content: "{{ secrets_crs.stdout }}"
    dest:  "{{scs_cs_user_home}}/.secret-crs"
    mode: 0440
  when: secrets_crs.changed

- name: Apply generated secret for "CRS"
  become: true
  command: "{{k3s_bin}} kubectl apply -f {{scs_cs_user_home}}/.secret-crs"

- name: Install cluster stack operator
  become: true
  command: "helm upgrade --kubeconfig {{kubeconfig_path}} -i cso -n cso-system --create-namespace {{scs_cs_repo_cso}}"

- name: Request rollout status for cluster stack operator
  become: true
  command: "{{ k3s_bin }} kubectl -n cso-system rollout status deployment"
