---
- name: Template "clouds.yaml"
  become: true
  template:
    src: openstack-clouds.yaml.j2
    dest: "{{openstack_clouds_yaml}}"
    mode: 0444

- name: Template "envsubst-helper.sh"
  become: true
  template:
    src: envsubst-helper.sh.j2
    dest: "{{ envsubst_helper }}"
    mode: 0444

# - name: Template "scs-operator.yaml"
#   become: true
#   template:
#     src: scs-operator.yaml.j2
#     dest: "{{scs_cluster_stack_home}}/scs-operator.yaml"
#     mode: 0444

- name: Check if "{{scs_cluster_stack_operator_specs_yaml}}" exists
  become: true
  stat:
    path: "{{ scs_cluster_stack_operator_specs_yaml }}"
  register: check_scs_cluster_stack_operator_specs_yaml

- name: Get "{{scs_cluster_stack_operator_specs_yaml}}"
  become: true
  get_url:
    url: "{{ scs_cluster_stack_operator_specs }}"
    dest: "{{ scs_cluster_stack_operator_specs_yaml }}"
    mode: 0640
  when: not check_scs_cluster_stack_operator_specs_yaml.stat.exists
  register: get_scs_cluster_stack_operator_specs_yaml

- name: envsubst "{{scs_cluster_stack_operator_specs_yaml}}" using "envsubst-helper.sh"
  become: true
  command: /bin/sh {{ envsubst_helper }} {{ scs_cluster_stack_operator_specs_yaml }} {{ scs_cluster_stack_operator_specs_yaml }}.envsubst
  when: get_scs_cluster_stack_operator_specs_yaml.changed

- name: Apply operator specs for SCS
  become: true
  command: "{{ k3s_bin }} kubectl apply -f {{ scs_cluster_stack_operator_specs_yaml }}.envsubst"
  environment:
    - CLUSTER_TOPOLOGY: true
    - EXP_CLUSTER_RESOURCE_SET: true
    - EXP_RUNTIME_SDK: true
