---
- name: Template "clouds.yaml"
  become: true
  template:
    src: openstack-clouds.yaml.j2
    dest: "{{openstack_clouds_yaml}}"
    mode: 0444

- name: Template "scs-operator.yaml""
  become: true
  template:
    src: scs-operator.yaml.j2
    dest: "{{scs_cluster_stack_home}}/scs-operator.yaml"
    mode: 0444

- name: Check if "{{scs_cluster_stack_operator_specs_yaml}}" exists
  stat:
    path: "{{ scs_cluster_stack_operator_specs_yaml }}"
  register: check_scs_cluster_stack_operator_specs_yaml

- name: Get "{{scs_cluster_stack_operator_specs_yaml}}"
  become: true
  get_url:
    url: "{{ scs_cluster_stack_operator_specs }}"
    dest: "{{ scs_cluster_stack_operator_specs_yaml }}"
    mode: 0640
  when: not check_scs_cluster_stack_operator_specs_yaml.stat.exists
  register: get_scs_cluster_stack_operator_specs_yaml

- name: envsubst "{{scs_cluster_stack_operator_specs_yaml}}"
  become: true
  command:
    cmd: |
      {{envsubst_bin}} {{ scs_cluster_stack_operator_specs_yaml }} \
      > {{ scs_cluster_stack_operator_specs_yaml }}.envsubst
  when: get_scs_cluster_stack_operator_specs_yaml.changed

- name: Apply operator specs for SCS
  become: true
  shell:
    cmd: |
      source {{scs_cluster_stack_home}}/capi-k8s-vars.rc \
      && {{ k3s_bin }} kubectl apply -f {{ scs_cluster_stack_operator_specs_yaml }}.envsubst
  args:
    executable: /bin/bash

- name: Apply provider specs for SCS
  become: true
  shell:
    cmd: |
      source {{scs_cluster_stack_home}}/capi-k8s-vars.rc \
      && curl -sSL {{scs_cluster_stack_provider_specs}} | {{ envsubst_bin }} | {{ k3s_bin }} kubectl apply -f -
  args:
    executable: /bin/bash

- name: Install cluster stack helper via 'Helm'
  become: true
  shell:
    cmd: |
      source {{scs_cluster_stack_home}}/capi-k8s-vars.rc \
      && helm upgrade --create-namespace \
         -i csp-helper-{{cluster_namespace}} \
         -n {{cluster_namespace}} \
         {{scs_cluster_stack_helper}} -f {{openstack_clouds_yaml}}
         
  args:
    executable:  /bin/bash
  environment:
    - CLUSTER_TOPOLOGY: true
    - EXP_CLUSTER_RESOURCE_SET: true
    - EXP_RUNTIME_SDK: true
