---
- name: Check if "{{scs_cluster_stack_provider_specs_yaml}}" exists
  become: true
  stat:
    path: "{{ scs_cluster_stack_provider_specs_yaml }}"
  register: check_scs_cluster_stack_provider_specs_yaml

- name: Get "{{scs_cluster_stack_provider_specs_yaml}}"
  become: true
  get_url:
    url: "{{ scs_cluster_stack_provider_specs }}"
    dest: "{{ scs_cluster_stack_provider_specs_yaml }}"
    mode: 0640
  when: not check_scs_cluster_stack_provider_specs_yaml.stat.exists
  register: get_scs_cluster_stack_provider_specs_yaml

- name: envsubst "{{scs_cluster_stack_provider_specs_yaml}}" using "envsubst-helper.sh"
  become: true
  command: /bin/sh {{ envsubst_helper }} {{ scs_cluster_stack_provider_specs_yaml }} {{ scs_cluster_stack_provider_specs_yaml }}.envsubst
  when: get_scs_cluster_stack_provider_specs_yaml.changed

- name: Apply provider specs for SCS
  become: true
  command: "{{ k3s_bin }} kubectl apply -f {{ scs_cluster_stack_provider_specs_yaml }}.envsubst"

- name: Install cluster stack helper
  become: true
  command: "helm upgrade --create-namespace --kubeconfig {{kubeconfig_path}} -i csp-helper-{{cluster_namespace}} -n {{cluster_namespace}} {{scs_cluster_stack_helper}} -f {{openstack_clouds_yaml}}"
