---
- name: Template "cloud.conf"
  become: true
  template:
    src: cloud.conf.j2
    dest: "{{openstack_cloud_conf_path}}"
    mode: 0440

- name: Create symbolic link to "k3s-cloud.conf"
  become: true
  file:
    dest: "/root/.config/openstack/cloud.conf"
    src: "{{openstack_cloud_conf_path}}"
    state: link

- name: Encode "cloud.conf" into base64
  become: true
  command: "base64 -w 0 {{openstack_cloud_conf_path}}"
  register: stdout_base64_cloud_conf

- name: Set fact from encoded "cloud.conf"
  set_fact:
    k3s_cloud_conf_b64: "{{ stdout_base64_cloud_conf.stdout }}"

- name: Setup cloud credentials using 'k3s'
  block:
    
    - name: Template "k3s-cloud-config.yaml"
      become: true
      template:
        src: k3s-cloud-config.yaml.j2
        dest: "{{scs_cs_user_home}}/k3s-cloud-config.yaml"
        mode: 0440
    
    - name: Apply "k3s-cloud-config.yaml"
      become: true
      command: "kubectl apply -f {{scs_cs_user_home}}/k3s-cloud-config.yaml"

  when: k3s_apply_role | bool
