---
- name: Template "scs-specs-clusterstack.yaml"
  become: true
  template:
    src: scs-specs-clusterstack.yaml.j2
    dest: "{{scs_cluster_stack_home}}/scs-specs-clusterstack.yaml"
    mode: 0444

- name: Template "scs-specs-workloadcluster.yaml"
  become: true
  template:
    src: scs-specs-workloadcluster.yaml.j2
    dest: "{{scs_cluster_stack_home}}/scs-specs-workloadcluster.yaml"
    mode: 0444

- name: Apply specs from "scs-specs-clusterstack.yaml"
  become: true
  command: "{{ k3s_bin }} kubectl apply -f {{scs_cluster_stack_home}}/scs-specs-clusterstack.yaml"
  environment:
    - CLUSTER_TOPOLOGY: true
    - EXP_CLUSTER_RESOURCE_SET: true
    - EXP_RUNTIME_SDK: true

- name: Apply specs from "scs-specs-workloadcluster.yaml"
  become: true
  command: "{{ k3s_bin }} kubectl apply -f {{scs_cluster_stack_home}}/scs-specs-workloadcluster.yaml"
  environment:
    - CLUSTER_TOPOLOGY: true
    - EXP_CLUSTER_RESOURCE_SET: true
    - EXP_RUNTIME_SDK: true

- name: Ensure ".config" directory exists for "root"
  become: true
  file:
    mode: 0750
    owner: "root"
    path: "/root/.config"
    recurse: yes
    state: directory

- name: Create symbolic link to ".config/openstack"
  become: true
  file:
    dest: "/root/.config/openstack"
    src: "{{scs_cluster_stack_home}}/.config/openstack"
    state: link
