---
- name: Template "k3s-cloud.conf"
  become: true
  template:
    src: k3s-cloud.conf.j2
    dest: "{{scs_cs_user_home}}/.config/k3s-cloud.conf"
    mode: 0440

- name: Create symbolic link to "k3s-cloud.conf"
  become: true
  file:
    dest: "/root/.config/k3s-cloud.conf"
    src: "{{scs_cs_user_home}}/.config/k3s-cloud.conf"
    state: link

- name: Encode "k3s-cloud.conf" into base64
  become: true
  command: "base64 -w 0 {{scs_cs_user_home}}/.config/k3s-cloud.conf"
  register: stdout_base64_k3s_cloud_conf

- name: Set fact from encoded "k3s-cloud.conf"
  set_fact:
    k3s_cloud_conf_b64: "{{ stdout_base64_k3s_cloud_conf.stdout }}"

- name: Template "k3s-cloud-config.yaml"
  become: true
  template:
    src: k3s-cloud-config.yaml.j2
    dest: "{{scs_cs_user_home}}/k3s-cloud-config.yaml"
    mode: 0440

- name: Apply "k3s-cloud-config.yaml"
  become: true
  command: "kubectl apply -f {{scs_cs_user_home}}/k3s-cloud-config.yaml"
