---
- name: Template "k3s-cloud.conf"
  become: true
  template:
    src: k3s-cloud.conf.j2
    dest: "{{scs_cs_user_home}}/.config/k3s-cloud.conf"
    mode: 0440

- name: Create symbolic link to "k3s-cloud.conf"
  become: true
  file:
    dest: "/root/.config/k3s-cloud.conf"
    src: "{{scs_cs_user_home}}/.config/k3s-cloud.conf"
    state: link

- name: Encode "k3s-cloud.conf"
  become: true
  set_fact:
    k3s_cloud_conf_b64: "{{ lookup('file', '/root/.config/k3s-cloud.conf') | b64encode }}"

- name: Template "k3s-cloud-config.yaml"
  become: true
  template:
    src: k3s-cloud-config.yaml.j2
    dest: "{{scs_cs_user_home}}/k3s-cloud-config.yaml"
    mode: 0440

- name: Apply "k3s-cloud-config.yaml"
  become: true
  command: "{{ k3s_bin }} kubectl apply -f {{scs_cs_user_home}}/k3s-cloud-config.yaml"
