---
- name: Template "scs-resourceset.yaml"
  become: true
  template:
    src: scs-resourceset.yaml.j2
    dest: "{{scs_cluster_stack_home}}/scs-resourceset.yaml"
    mode: 0444

- name: Template "scs-specs-clusterstack.yaml"
  become: true
  template:
    src: scs-specs-clusterstack.yaml.j2
    dest: "{{scs_cluster_stack_home}}/scs-specs-clusterstack.yaml"
    mode: 0444

- name: Template "scs-specs-workloadcluster.yaml"
  become: true
  template:
    src: scs-specs-workloadcluster.yaml.j2
    dest: "{{scs_cluster_stack_home}}/scs-specs-workloadcluster.yaml"
    mode: 0444

- name: Apply specs from "scs-resourceset.yaml"
  become: true
  command: "{{ k3s_bin }} kubectl apply --validate=false -f {{scs_cluster_stack_home}}/scs-resourceset.yaml"

- name: Apply specs from "scs-specs-clusterstack.yaml"
  become: true
  command: "{{ k3s_bin }} kubectl apply -f {{scs_cluster_stack_home}}/scs-specs-clusterstack.yaml"

- name: Apply specs from "scs-specs-workloadcluster.yaml"
  become: true
  command: "{{ k3s_bin }} kubectl apply -f {{scs_cluster_stack_home}}/scs-specs-workloadcluster.yaml"
