---
- name: Include distribution-specific variables for Debian
  include_vars:
    dir: vars
    files_matching: "debian*"
    extensions: [ yml ]
  when: ansible_distribution == 'Debian'

- name: Include distribution-specific variables for Ubuntu
  include_vars:
    dir: vars
    files_matching: "ubuntu*"
    extensions: [ yml ]
  when: ansible_distribution == 'Ubuntu'

- name: Include base tasks to install dependencies and user account
  include_tasks: "{{ t }}"
  loop:
    - 00-install-dependencies.yml
    - 01-install-account.yml
  loop_control:
    loop_var: t

- name: Include all other "setup" tasks
  include_tasks: "{{ t }}"
  loop:
    - 02-setup-docker.yml
    - 03-setup-k3s.yml
    - 04-setup-components.yml
    - 05-setup-modules-sysctl.yml
    - 06-setup-capi-capo.yml
    - 07-setup-cso.yml
    - 08-setup-csp.yml
    - 09-setup-stack.yml
  loop_control:
    loop_var: t
  when: not scripts_only

- name: Template "tool-install" scripts
  become: true
  template:
    src: "{{s}}.j2"
    dest: "{{scs_cluster_stack_home}}/{{s}}"
    mode: 0555
  loop:
    - tool-install-clusterctl.sh
    - tool-install-docker.sh
    - tool-install-helm.sh
    - tool-install-kind.sh
    - tool-install-kubectl.sh
    - tool-install-oras.sh
  loop_control:
    loop_var: s

- name: Copy over scripts from "scs2" cluster-stack repository documentation
  become: true
  copy:
    src: "files/{{s}}"
    dest: "{{scs_cluster_stack_home}}/{{s}}"
    mode: 0555
  loop:
    - 001.sh
    - 002.sh
    - 003.sh
    - 004.sh
    - 005.sh
    - 006.sh
    - 007.sh
    - 008.sh
  loop_control:
    loop_var: s
